# coding: utf-8
from sqlalchemy import CHAR, Column, DECIMAL, DateTime, Float, String, TIMESTAMP, text
from sqlalchemy.dialects.mysql import INTEGER, TINYINT
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class PS(Base):
    __tablename__ = 'ps'

    pn = Column(String(50), primary_key=True, nullable=False, server_default=text("''"))
    pa = Column(String(50), primary_key=True, nullable=False, server_default=text("'P/A'"))
    LUSER = Column(String(40), nullable=False, server_default=text("''"))
    LDATE = Column(TIMESTAMP, nullable=False, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    LCHNG = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    ORIGIN = Column(String(20), nullable=False, server_default=text("''"))
    created = Column(DateTime)
    owner = Column(String(40), nullable=False, index=True, server_default=text("''"))
    mn = Column(String(255), nullable=False, index=True, server_default=text("''"))
    levels = Column(String(255), nullable=False, server_default=text("''"))
    commodity_code = Column(String(255), nullable=False, server_default=text("''"))
    product_code = Column(String(255), nullable=False, server_default=text("''"))
    buyer = Column(String(4), nullable=False, server_default=text("''"))
    make_buy = Column(String(5), nullable=False, server_default=text("'X'"))
    saleable = Column(CHAR(1), nullable=False, server_default=text("''"))
    traceable = Column(String(20), nullable=False, server_default=text("''"))
    trace_level = Column(TINYINT(4))
    new_part = Column(String(40), nullable=False, index=True, server_default=text("'ENGINEERING USE ONLY'"))
    ed = Column(String(255), nullable=False, index=True, server_default=text("''"))
    rv = Column(String(25))
    rvd = Column(DateTime)
    hold = Column(String(20), nullable=False, index=True, server_default=text("''"))
    wt = Column(Float, nullable=False, server_default=text("'0'"))
    wtu = Column(String(10), nullable=False, server_default=text("''"))
    shipping_length = Column(DECIMAL(20, 4), nullable=False, server_default=text("'0.0000'"))
    shipping_width = Column(DECIMAL(20, 4), nullable=False, server_default=text("'0.0000'"))
    shipping_depth = Column(DECIMAL(20, 4), nullable=False, server_default=text("'0.0000'"))
    volume = Column(DECIMAL(20, 4), nullable=False, server_default=text("'0.0000'"))
    volume_unit = Column(String(20), nullable=False, server_default=text("''"))
    unit = Column(String(10), nullable=False, server_default=text("''"))
    po_unit = Column(String(10), nullable=False, server_default=text("''"))
    po_unit_rate = Column(DECIMAL(20, 4), server_default=text("'1.0000'"))
    comment = Column(String(255), nullable=False, server_default=text("''"))
    dwg_num = Column(String(20), nullable=False, server_default=text("''"))
    dwg = Column(String(40), nullable=False, server_default=text("''"))
    bom = Column(String(3), nullable=False, server_default=text("''"))
    wi = Column(String(2), nullable=False, server_default=text("''"))
    picturer = Column(CHAR(1), nullable=False, server_default=text("''"))
    material = Column(String(10), nullable=False, server_default=text("''"))
    act_part = Column(CHAR(1), nullable=False, server_default=text("'Y'"))
    sales_dwg = Column(CHAR(1), nullable=False, server_default=text("''"))
    catalog = Column(String(10), nullable=False, server_default=text("''"))
    isdeleted = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    security_level = Column(CHAR(1), nullable=False, server_default=text("''"))
    eng_group = Column(String(40), nullable=False, server_default=text("''"))
    detection_standard = Column(String(20), nullable=False, server_default=text("''"))
    country_origin = Column(String(50), nullable=False, server_default=text("''"))
    inspection_type = Column(String(30), nullable=False, server_default=text("''"))
    ir_type = Column(String(30), nullable=False, server_default=text("''"))
    recoil = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    use_backflush = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    discountable = Column(TINYINT(1), nullable=False, server_default=text("'1'"))
    tax_exempt = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    multi_qty_for_applying = Column(DECIMAL(8, 4), nullable=False, server_default=text("'0.0000'"))
    hs_code = Column(String(20), nullable=False, server_default=text("''"))
    checkstatus = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    check_comment = Column(String(255), nullable=False, server_default=text("''"))
    part_code = Column(String(50), nullable=False, server_default=text("''"))
    catalog_ext = Column(String(45), comment='物料分类')